
-- Seed Offices and SubOffices for all Organizations
USE [TABDB];
GO

SET NOCOUNT ON;

PRINT '================================================================';
PRINT 'SEEDING OFFICES AND SUBOFFICES';
PRINT '================================================================';
PRINT '';

-- Temporary table to hold the data
CREATE TABLE #TempOfficeData (
    OrgCode NVARCHAR(50),
    OfficeName NVARCHAR(200),
    SubOfficeName NVARCHAR(200)
);

-- Insert all the data
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- CON (Consultancy) offices
('CON', 'BCD TRAVEL', 'Central Area'),
('CON', 'BM Security', 'Central Area'),
('CON', 'CAFE ROYALE', 'Central Area'),
('CON', 'CEN-ELEC', 'H-2'),
('CON', 'CIGNA', 'Central Area'),
('CON', 'COMMISSARY', 'CMMF'),
('CON', 'COMMISSARY', 'New Commissary Bld'),
('CON', 'COMPUTECH', 'W-1 WEST WING'),
('CON', 'COOP. BANK', 'Central Area'),
('CON', 'COOP. BANK', 'CO-OP BANK'),
('CON', 'COOP. BANK', 'Gigiri Square'),
('CON', 'COOP. BANK/CS', 'CO-OP BANK'),
('CON', 'DHL', 'Central Area'),
('CON', 'DIANI FLOWERS', 'Gardener''s Shed'),
('CON', 'EXPRESS', 'Central Area'),
('CON', 'FLEMINGO', 'CMMF'),
('CON', 'FLEMINGO', 'New Commissary Bld'),
('CON', 'G4S SECURITY', 'Central Area'),
('CON', 'HEM TRAVEL', 'Central Area'),
('CON', 'HEM TRAVEL', 'E-225'),
('CON', 'KADAI KING', 'Old Cafeteria'),
('CON', 'KCB', 'Central Area'),
('CON', 'KK SECURITY', 'Central Area'),
('CON', 'MFI', 'PREFAB-6'),
('CON', 'ORAD', 'Fire Station'),
('CON', 'PCC', 'H-2'),
('CON', 'PEGRUME', 'G-115'),
('CON', 'PETROL', 'PETROL STATION'),
('CON', 'POST', 'Central Area'),
('CON', 'RADAR', 'Central Area'),
('CON', 'RINA', 'H-2'),
('CON', 'River Cafe', 'Central Area'),
('CON', 'River Cafe', 'NOF BLOCK 1-2'),
('CON', 'River Cafe', 'NOF BLOCK 2-3'),
('CON', 'River Cafe', 'NOF BLOCK 3-4'),
('CON', 'River Cafe', 'RECREATION CENTRE'),
('CON', 'SAFARI PARK', 'Central Area'),
('CON', 'SAFARI PARK', 'M-LEVEL-2'),
('CON', 'SAFARI PARK', 'P-LEVEL-2'),
('CON', 'SAFARI PARK', 'R-LEVEL-2'),
('CON', 'SAFARI PARK', 'S-LEVEL-2'),
('CON', 'SAFARI PARK', 'W-BLOCK'),
('CON', 'SCB', 'Central Area'),
('CON', 'SECUREX', 'Central Area'),
('CON', 'TGFC', 'NOF BLOCK 1-2'),
('CON', 'TGFC', 'NOF BLOCK 2-3'),
('CON', 'TGFC', 'NOF BLOCK 3-4'),
('CON', 'TNT', 'Central Area'),
('CON', 'TRANSAMI', 'Central Area'),
('CON', 'UCH', 'Central Area'),
('CON', 'ULTIMATE', 'Central Area'),
('CON', 'UNFCU', 'Central Area'),
('CON', 'UNFCU', 'E-LEVEL-2'),
('CON', 'UNFCU', 'LOWER LIB'),
('CON', 'UNIASC', 'Central Area'),
('CON', 'VANBREDA', 'Central Area'),

-- DSS offices
('DSS', 'DSS DRO AS KENYA', NULL),

-- FAO offices
('FAO', 'KENYA', 'P-LEVEL-2'),
('FAO', 'KENYA', 'P-LEVEL-3'),
('FAO', 'REOA', 'P-LEVEL-2'),
('FAO', 'REOA', 'P-LEVEL-3'),

-- ICAO offices
('ICAO', 'ESAF', 'NOF BLOCK 4-1 SW'),
('ICAO', 'ESAF/ADM', 'NOF BLOCK 4-1 SW'),
('ICAO', 'ESAF/AGA', 'NOF BLOCK 4-1 SW'),
('ICAO', 'ESAF/ATM', 'NOF BLOCK 4-1 SW'),
('ICAO', 'ESAF/RO', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/ADM', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/ATM', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/AVSEC', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/DRD', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/FO', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/FS', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/MET', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/OPS', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/RD', 'NOF BLOCK 4-1 SW'),
('ICAO', 'RO/TCB', 'NOF BLOCK 4-1 SW'),
('ICAO', 'SOM', 'ICAO House'),
('ICAO', 'SOM', 'ICAO Somalia House'),

-- ICC offices
('ICC', 'ICC-CPI', 'Block - X'),
('ICC', 'ICC-CPI', 'X-Level-3'),

-- ICC-CPI offices
('ICC-CPI', 'ICC-CPI', 'X-2 EAST WING'),
('ICC-CPI', 'ICC-CPI', 'X-225'),
('ICC-CPI', 'ICC-CPI', 'X-level-2 EW'),

-- IFAD offices (extensive list)
('IFAD', 'ACP/ADM', 'Block U Level-1'),
('IFAD', 'ADM', 'Block - U'),
('IFAD', 'Block Q', NULL),
('IFAD', 'CFS', 'U-LEVEL-1'),
('IFAD', 'CFS', 'X-3 WEST WING'),
('IFAD', 'CSD', 'U-LEVEL-1'),
('IFAD', 'ESA', NULL),
('IFAD', 'ESA', 'BLK'),
('IFAD', 'ESA', 'BLOCK U Level 1'),
('IFAD', 'ESA', 'Block U Level-1'),
('IFAD', 'ESA', 'N-BLK'),
('IFAD', 'ESA', 'PREFAB'),
('IFAD', 'ESA', 'PREFABS'),
('IFAD', 'ESA', 'T-BLK'),
('IFAD', 'ESA', 'T-BLOCK'),
('IFAD', 'ESA', 'Training Room'),
('IFAD', 'ESA', 'U-BLK'),
('IFAD', 'ESA', 'U-LEVEL-1'),
('IFAD', 'ESA', 'U-LEVEL-2'),
('IFAD', 'ESA', 'X-1 East Wing'),
('IFAD', 'ESA - IFAD', NULL),
('IFAD', 'ESA Regional Office', NULL),
('IFAD', 'ESA/ADM/PMU', 'Block U Level-1'),
('IFAD', 'IFAD', NULL),
('IFAD', 'IFAD', 'BLK'),
('IFAD', 'IFAD', 'BLK-Q'),
('IFAD', 'IFAD', 'Block Q'),
('IFAD', 'IFAD', 'Block U-101'),
('IFAD', 'IFAD', 'Central'),
('IFAD', 'IFAD', 'IFAD'),
('IFAD', 'IFAD', 'P-BLK'),
('IFAD', 'IFAD', 'Q-BLK'),
('IFAD', 'IFAD', 'T-BLK'),
('IFAD', 'IFAD', 'U-Level 1'),
('IFAD', 'IFAD', 'U-LEVEL-1'),
('IFAD', 'IFAD', 'U-LEVEL-2'),
('IFAD', 'IFAD', 'X-1 East Wing'),
('IFAD', 'IFAD', 'X-1 West Wing'),
('IFAD', 'IFAD', 'X-3 EAST WING'),
('IFAD', 'IFAD', 'X-3 WEST WING'),
('IFAD', 'IFAD', 'X-blk'),
('IFAD', 'IFAD', 'X-level-1'),
('IFAD', 'IFAD ESA', 'P-BLK'),
('IFAD', 'IFAD ESA RO', 'P-BLK'),
('IFAD', 'KENYA/ADM/FSU', NULL),
('IFAD', 'KENYA/ADM/FSU', 'blk'),
('IFAD', 'KENYA/ADM/FSU', 'Block Q'),
('IFAD', 'KENYA/ADM/FSU', 't-blk'),
('IFAD', 'Nairobi', NULL),
('IFAD', 'RO', 'BLK'),
('IFAD', 'RO', 'Block U Level 1'),
('IFAD', 'RO', 'Central'),
('IFAD', 'RO', 'T-BLK'),
('IFAD', 'RO', 'U-BLK'),

-- ILO offices
('ILO', 'KENYA', 'P-LEVEL-1'),
('ILO', 'SOMALIA', 'P-LEVEL-1'),
('ILO', 'SOMALIA', 'P-LEVEL-2'),

-- IMO offices
('IMO', 'IMO', 'M-LEVEL-1'),
('IMO', 'IMO', 'M-LEVEL-2'),

-- OHCHR offices
('OHCHR', 'FFM SUDAN', NULL),
('OHCHR', 'FFM/SUDAN', 'PREFAB'),
('OHCHR', 'FFM/Sudan', 'Prefab D4'),
('OHCHR', 'FFM/Sudan', 'PREFAB-D'),
('OHCHR', 'MCO', NULL),
('OHCHR', 'MCO', 'A-BLK'),
('OHCHR', 'MCO', 'T-BLK'),
('OHCHR', 'MCO', 'W-blk'),
('OHCHR', 'MCO', 'X-BLK'),
('OHCHR', 'NAIROBI', 'PREFAB-D'),
('OHCHR', 'ODHC', 'T-BLK'),
('OHCHR', 'OHCHR', NULL),
('OHCHR', 'OHCHR', 'OHCHR'),
('OHCHR', 'OHCHR', 'Prefab D4'),
('OHCHR', 'OHCHR  FFM Sudan', 'PREFAB-D'),
('OHCHR', 'OHCHR FFM Sudan', NULL),
('OHCHR', 'OHCHR FFM Sudan', 'PREFAB-D'),
('OHCHR', 'OHCHR ODHC FOTCD', 'A-BLK'),
('OHCHR', 'OHCHR ODHC FOTCD', 'W-blk'),
('OHCHR', 'OHCHR ODHC FOTCD AB CO UGANDA', NULL),
('OHCHR', 'OHCHR ODHC FOTCD AB CO UGANDA', 'X-BLK'),
('OHCHR', 'OHCHR Sudan', 'W-BLK'),
('OHCHR', 'SUDAN', NULL),
('OHCHR', 'Sudan', 'Prefab'),
('OHCHR', 'SUDAN', 'Prefab S1'),
('OHCHR', 'SUDAN', 'PREFABS'),
('OHCHR', 'SUDAN', 'W-BLK'),
('OHCHR/FFM', 'FFM Sudan', NULL),

-- OIOS offices
('OIOS', 'IAD', 'M-LEVEL-1'),
('OIOS', 'IAD', 'U-224'),
('OIOS', 'IAD', 'U-225'),
('OIOS', 'IAD', 'U-232'),
('OIOS', 'IAD', 'U-236'),
('OIOS', 'IAD', 'U-LEVEL-2'),
('OIOS', 'ID', 'M-BLK'),
('OIOS', 'INV', 'Block U L1'),
('OIOS', 'INV', 'Block U Level-1'),
('OIOS', 'INV', 'Block U, Lower'),
('OIOS', 'INV/UNIT II SEC', 'I-1'),
('OIOS', 'INV/UNIT II SEC', 'U-LEVEL 1'),
('OIOS', 'INV/UNIT II SEC', 'U-LEVEL-1'),
('OIOS', 'INV/UNIT II&IV', 'U-LEVEL-1'),
('OIOS', 'INV/UNIT IV', 'U-LEVEL 1'),
('OIOS', 'INV/UNIT IV SEC', 'Block U Level 1'),
('OIOS', 'INV/UNIT IV SEC', 'U-LEVEL-1'),
('OIOS', 'OIOS', NULL),
('OIOS', 'OIOS', 'Block U'),
('OIOS', 'OIOS', 'Block U Level 1'),
('OIOS', 'OIOS', 'Block U-101'),
('OIOS', 'OIOS', 'Block U-Level 1'),
('OIOS', 'OIOS', 'X-1 East Wing'),
('OIOS', 'OIOS ID ENTEBBE', 'h'),
('OIOS', 'OIOS ID ENTEBBE NAIROBI', 'BLK'),
('OIOS', 'OIOS ID ENTEBBE NAIROBI', 'fgh'),
('OIOS', 'OIOS ID ENTEBBE NAIROBI', 'M-BLOCK'),
('OIOS', 'OIOS ID ENTEBBE NAIROBI', 'N-BLK'),
('OIOS', 'OIOS ID ENTEBBE NAIROBI', 'P-BLK'),
('OIOS', 'OIOS ID ENTEBBE NAIROBI', 'Q-BLK'),
('OIOS', 'OIOS ID ENTEBBE NAIROBI', 'UNON'),
('OIOS', 'OIOS ID NAIROBI', 'P-BLK'),
('OIOS', 'UNHCR', 'U-218'),
('OIOS', 'UNHCR', 'U-LEVEL-2');

-- Continue with more organizations...
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- OSESG offices
('OSESG', 'ADM/ADMIN/HRU', NULL),
('OSESG', 'GL', NULL),
('OSESG', 'GL', 'BLK'),
('OSESG', 'GL', 'BLK-1'),
('OSESG', 'GL', 'Block - R'),
('OSESG', 'GL', 'Block R level 3'),
('OSESG', 'GL', 'Block R Level-1'),
('OSESG', 'GL', 'BLOCK R-LEVEL-1'),
('OSESG', 'GL', 'BLOCK-R Level-3'),
('OSESG', 'GL', 'fg'),
('OSESG', 'GL', 'loc'),
('OSESG', 'GL', 'loc29999'),
('OSESG', 'GL', 'M-BLK'),
('OSESG', 'GL', 'N'),
('OSESG', 'GL', 'nof'),
('OSESG', 'GL', 'P-BLK'),
('OSESG', 'GL', 'r-blk'),
('OSESG', 'GL', 'R-Level 3'),
('OSESG', 'GL', 'R-LEVEL-2'),
('OSESG', 'GL', 'R-LEVEL-3'),
('OSESG', 'GL', 'r-level2'),
('OSESG', 'GL', 'R-nlb'),
('OSESG', 'GL', 'S-3 OPEN SPACE'),
('OSESG', 'GL', 'S-LEVEL-3'),
('OSESG', 'GL', 'S-Level=3'),
('OSESG', 'GL', 'W-1'),
('OSESG', 'GL', 'WWWW'),
('OSESG', 'GL', 'X'),
('OSESG', 'OSESG', NULL),
('OSESG', 'OSESG', 'Block R Level-1'),
('OSESG', 'OSESG', 'Block R Level-3'),
('OSESG', 'OSESG', 'fd'),
('OSESG', 'OSESG', 'loc'),
('OSESG', 'OSESG', 'R - Level -3'),
('OSESG', 'OSESG', 'R-301'),
('OSESG', 'OSESG', 'S-BLOCK'),
('OSESG', 'OSESG', 'we'),
('OSESG', 'PAU', 'R-BLOCK'),
('OSESG-GL', 'BLOCK S-3', NULL),

-- Continue with remaining organizations
('POESOM', 'ADM', 'Block S'),
('POESOM', 'POESOM', NULL),
('POESOM', 'POESOM', 'BLOCK S'),
('POESOM', 'POESOM', 'Block S Level-2'),
('POESOM', 'POESOM', 'Block-S Level 1'),
('POESOM', 'POESOM', 'P-LEVEL-1'),
('POESOM', 'POESOM', 'S-LEVEL-2'),
('POESOM', 'POESOM', 'T-BLK'),
('POESOM', 'POESOM', 'W-1WW'),
('POESOM', 'POESOM', 'Wrong Number'),
('POESOM', 'POESOM NAIRO', NULL),
('POESOM', 'POESOM NAIRO', 'Prefab'),
('POESOM', 'POESOM NAIRO', 'X-blk'),

-- RCO offices
('RCO', 'Kenya', NULL),
('RCO', 'KENYA', 'Block - X'),
('RCO', 'KENYA', 'Block M L3'),
('RCO', 'KENYA', 'Block R Level-1'),
('RCO', 'KENYA', 'Block X-101'),
('RCO', 'KENYA', 'M-BLK'),
('RCO', 'KENYA', 'M-LEVEL-3'),
('RCO', 'KENYA', 'N-LEVEL-3'),
('RCO', 'KENYA', 'PREFAB'),
('RCO', 'KENYA', 'R-blk'),
('RCO', 'KENYA/RCLLA', 'R-BLK'),
('RCO', 'RCO RCLLA', 'M-BLK'),
('RCO', 'RCO-Kenya', NULL),
('RCO', 'RCS RCO RCLLA KEN', 'R-BLK'),
('RCO', 'SOMALIA', 'PREFAB'),
('RCO', 'SOMALIA', 'S-3 OPEN SPACE'),
('RCO', 'SOMALIA', 'S-LEVEL-1'),
('RCO', 'SOMALIA', 'S-LEVEL-2'),
('RCO', 'SOMALIA', 'V-block'),
('RCO', 'UNON', 'UNON'),

-- RCS offices
('RCS', 'RCS RCO RCLLA KEN', NULL),

-- UN-WOMEN offices
('UN-WOMEN', 'KCO', 'M-LEVEL-1'),
('UN-WOMEN', 'KCO', 'M-LEVEL-2'),
('UN-WOMEN', 'KCO', 'M-LEVEL-3'),
('UN-WOMEN', 'RO', 'M-LEVEL-1'),
('UN-WOMEN', 'RO', 'M-LEVEL-2'),
('UN-WOMEN', 'RO', 'NOF BLOCK 1-2 SW'),
('UN-WOMEN', 'UN-WOMEN', 'M-LEVEL-1'),
('UN-WOMEN', 'UN-WOMEN', 'M-LEVEL-2'),
('UN-WOMEN', 'UN-WOMEN', 'M-LEVEL-3'),
('UN-WOMEN', 'UN-WOMEN', 'M-LEVEL1'),
('UN-WOMEN', 'UN-WOMEN', 'N-1 OPEN'),
('UN-WOMEN', 'UN-WOMEN', 'N-LEVEL-1'),

-- UNAIDS offices
('UNAIDS', 'FRS', 'P-LEVEL-1'),
('UNAIDS', 'KCO', 'P-LEVEL-1'),
('UNAIDS', 'SOMALIA', 'P-LEVEL-1'),
('UNAIDS', 'UNAIDS', NULL),
('UNAIDS', 'UNAIDS', 'M-LEVEL-2'),
('UNAIDS', 'UNAIDS', 'P-LEVEL-1'),

-- UNAMIS offices
('UNAMIS', 'UNAMIS', 'UNAMIS ANNEX'),

-- UNCRD offices
('UNCRD', 'UNCRD', 'A-131'),
('UNCRD', 'UNCRD', 'M-LEVEL-2'),

-- UNDEFINED offices
('UNDEFINED', 'UNHCR', 'X-BLOCK');

-- Continue with remaining UNDP offices and others
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- UNDP offices (extensive list)
('UNDP', 'DGU', 'M-LEVEL-3'),
('UNDP', 'DGU', 'N-LEVEL-3'),
('UNDP', 'DGU/AW', 'N-1 OPEN'),
('UNDP', 'DGU/AW', 'Prefap-3'),
('UNDP', 'ESARO', 'N-LEVEL-3'),
('UNDP', 'GPC', 'M-LEVEL-2'),
('UNDP', 'GPC', 'NOF BLOCK 1-2 SW'),
('UNDP', 'IRIN', 'X-3 EAST WING'),
('UNDP', 'KCO', 'M-LEVEL-2'),
('UNDP', 'KCO', 'N-LEVEL-1'),
('UNDP', 'KCO', 'N-LEVEL-3'),
('UNDP', 'KCO', 'NOF BLOCK 1-1 SW'),
('UNDP', 'KCO', 'PREFAB-D4'),
('UNDP', 'KCO/ADMIN', 'M-LEVEL-3'),
('UNDP', 'KCO/ADMIN', 'N-LEVEL-3'),
('UNDP', 'KCO/AMKENI', 'N-LEVEL-3'),
('UNDP', 'KCO/COMMS', 'M-LEVEL-3'),
('UNDP', 'KCO/DGU', 'M-LEVEL-3'),
('UNDP', 'KCO/DGU', 'N-LEVEL-1'),
('UNDP', 'KCO/DGU', 'N-LEVEL-3'),
('UNDP', 'KCO/DRRRU', 'M-LEVEL-3'),
('UNDP', 'KCO/DRRRU', 'N-LEVEL-1'),
('UNDP', 'KCO/DSS', 'G-101'),
('UNDP', 'KCO/DSS', 'G-210'),
('UNDP', 'KCO/DSS', 'G-219'),
('UNDP', 'KCO/DSS', 'G-227'),
('UNDP', 'KCO/DSS', 'G-231'),
('UNDP', 'KCO/DSS', 'Swing Space'),
('UNDP', 'KCO/EECU', 'M-LEVEL-3'),
('UNDP', 'KCO/FINANCE', 'N-LEVEL-3'),
('UNDP', 'KCO/FO', 'M-LEVEL-3'),
('UNDP', 'KCO/FO', 'N-LEVEL-3'),
('UNDP', 'KCO/HR', 'M-LEVEL-3'),
('UNDP', 'KCO/HR', 'N-LEVEL-3'),
('UNDP', 'KCO/ICT', 'N-LEVEL-1'),
('UNDP', 'KCO/ICTU', 'N-LEVEL-3'),
('UNDP', 'KCO/IEG', 'M-LEVEL-3'),
('UNDP', 'KCO/IEG', 'N-LEVEL-3'),
('UNDP', 'KCO/ITC', 'M-LEVEL-1'),
('UNDP', 'KCO/ITC', 'M-LEVEL-3'),
('UNDP', 'KCO/NP-RSCA', 'M-LEVEL-3'),
('UNDP', 'KCO/NP-RSCA', 'N-LEVEL-3'),
('UNDP', 'KCO/PBCPU', 'M-LEVEL-3'),
('UNDP', 'KCO/PM', 'M-LEVEL-3'),
('UNDP', 'KCO/PM', 'N-LEVEL-1'),
('UNDP', 'KCO/PROC', 'N-LEVEL-3'),
('UNDP', 'KCO/PTU', 'N-LEVEL-3'),
('UNDP', 'KCO/PU', 'N-LEVEL-1'),
('UNDP', 'KCO/PU', 'N-LEVEL-3'),
('UNDP', 'KCO/REG', 'N-LEVEL-3'),
('UNDP', 'KCO/RESCORD', 'M-LEVEL-3'),
('UNDP', 'KCO/RESCORD', 'M-LEVEL3'),
('UNDP', 'KCO/RESCORD', 'N-LEVEL-3'),
('UNDP', 'KCO/RESCORD', 'P-124'),
('UNDP', 'KCO/RESCORD', 'PREFAB-1'),
('UNDP', 'KCO/RESCORD/Gender', 'M-LEVEL-3'),
('UNDP', 'KCO/SECURITY', 'M-LEVEL-3'),
('UNDP', 'KCO/SECURITY', 'N-LEVEL-1'),
('UNDP', 'KCO/SITA', 'M-LEVEL-3'),
('UNDP', 'KCO/SITA', 'N-LEVEL-1'),
('UNDP', 'KCO/SITA', 'N-LEVEL-3'),
('UNDP', 'KCO/SPAU', 'M-LEVEL-3'),
('UNDP', 'KCO/TRANS', 'N-LEVEL-3'),
('UNDP', 'KCO/TRANS/TRANS', 'N-LEVEL-3'),
('UNDP', 'KCO/UNDG', 'NOF BLOCK 2-1 SW'),
('UNDP', 'KCO/UNDSS', 'G-210'),
('UNDP', 'KCO/UNDSS/DRO', 'G-216'),
('UNDP', 'KCO/UNOHCHR', 'N-LEVEL-1'),
('UNDP', 'KCO/UNV', 'M-LEVEL-3'),
('UNDP', 'KCO/UNV', 'M-LEVEL3'),
('UNDP', 'KCO/UNV', 'N-LEVEL-3'),
('UNDP', 'KSCO/DSS', 'G-BLOCK'),
('UNDP', 'PBCPU', 'M-LEVEL-3'),
('UNDP', 'SOMALIA', 'C-108'),
('UNDP', 'SOMALIA', 'PREFAB'),
('UNDP', 'SOMALIA', 'PREFAB-D1'),
('UNDP', 'SOMALIA', 'PREFAB-D2'),
('UNDP', 'SOMALIA', 'PREFAB-D4'),
('UNDP', 'SOMALIA', 'PREFAB-D5'),
('UNDP', 'SOMALIA/ADM', 'PREFAB-D1'),
('UNDP', 'SOMALIA/ADM', 'PREFAB-D5'),
('UNDP', 'SOMALIA/FIN', 'PREFAB-D1'),
('UNDP', 'SOMALIA/FIN', 'PREFAB-D5'),
('UNDP', 'SOMALIA/HR', 'PREFAB-D5'),
('UNDP', 'SOMALIA/ICT', 'PREFAB-D4'),
('UNDP', 'SOMALIA/PRO', 'PREFAB-D5'),
('UNDP', 'SOMALIA/REG', 'PREFAB-D5'),
('UNDP', 'SOMALIA/RMU', 'PREFAB-D1'),
('UNDP', 'SUDAN/SUDAN', 'OLS Annex'),
('UNDP', 'UNDP', 'N-LEVEL-1'),
('UNDP-REDD+', 'UNDP-REDD+', 'N-LEVEL-1'),
('UNDP-REDD+', 'UNDP-REDD+', 'P-LEVEL-1'),

-- UNDRR offices
('UNDRR', 'ROA', 'N-LEVEL-2'),

-- UNDSS offices
('UNDSS', 'UNDSS', NULL),

-- UNDT offices
('UNDT', 'NAIROBI', 'Central Area'),
('UNDT', 'UNDT', 'UNDT'),
('UNDT', 'UNDT-Nairobi', 'CENTRAL AREA'),

-- UNEP ODED offices
('UNEP ODED', 'UNEP ODED', NULL);

-- Continue with UNESCO offices
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- UNESCO offices
('UNESCO', 'ADM', 'C-101'),
('UNESCO', 'ADM', 'C-114'),
('UNESCO', 'ADM', 'C-202'),
('UNESCO', 'ADM', 'C-203'),
('UNESCO', 'ADM', 'C-208'),
('UNESCO', 'ADM', 'C-217'),
('UNESCO', 'ADM', 'C-221'),
('UNESCO', 'ADM', 'C-223'),
('UNESCO', 'ADM', 'C-225'),
('UNESCO', 'ADM', 'C-227'),
('UNESCO', 'CI', 'C-104'),
('UNESCO', 'CI', 'C-206'),
('UNESCO', 'CI', 'C-215'),
('UNESCO', 'CLT', 'C-100'),
('UNESCO', 'CLT', 'C-102'),
('UNESCO', 'DIRECTOR', 'C-202'),
('UNESCO', 'DIRECTOR', 'C-203'),
('UNESCO', 'DIRECTOR', 'C-204'),
('UNESCO', 'DIRECTOR', 'C-211'),
('UNESCO', 'DIRECTOR', 'C-226'),
('UNESCO', 'EDU', 'C-202'),
('UNESCO', 'EDU', 'C-207'),
('UNESCO', 'EDU', 'C-218'),
('UNESCO', 'EDU', 'C-220'),
('UNESCO', 'EDU', 'C-222'),
('UNESCO', 'EDU', 'C-224'),
('UNESCO', 'EDU', 'C-225'),
('UNESCO', 'EDU', 'C-227'),
('UNESCO', 'EDU', 'P-LEVEL-3'),
('UNESCO', 'EDU/HIV&AIDS', 'C-222'),
('UNESCO', 'RO', 'C-113'),
('UNESCO', 'RO', 'C-116'),
('UNESCO', 'RO', 'C-119'),
('UNESCO', 'RO', 'C-202'),
('UNESCO', 'RO', 'C-207'),
('UNESCO', 'RO', 'C-224'),
('UNESCO', 'SC', 'C-105'),
('UNESCO', 'SC', 'C-202'),
('UNESCO', 'SC', 'C-216'),
('UNESCO', 'SC/ANSTI', 'C-215'),
('UNESCO', 'SC/ANSTI', 'C-216'),
('UNESCO', 'SC/EARTH', 'C-212'),
('UNESCO', 'SC/ECO', 'C-212'),
('UNESCO', 'SC/Gender', 'C-230'),
('UNESCO', 'SC/IOC', 'C-104'),
('UNESCO', 'SC/IOC', 'C-219'),
('UNESCO', 'SC/SHS', 'C-110'),

-- UNFPA offices
('UNFPA', 'HQ', NULL),
('UNFPA', 'HQ', 'Q-LEVEL-3'),
('UNFPA', 'KENYA', NULL),
('UNFPA', 'KENYA', 'N-LEVEL-2'),
('UNFPA', 'SOMALIA', 'N-LEVEL-2'),
('UNFPA', 'SOMALIA', 'P-LEVEL-2'),

-- UNHCR offices
('UNHCR', 'HR', 'PREFABs'),
('UNHCR', 'KENYA', 'PREFAB'),
('UNHCR', 'KENYA', 'PREFABs'),
('UNHCR', 'KENYA', 'X-3 EAST WING'),
('UNHCR', 'KENYA', 'X-3 WEST WING'),
('UNHCR', 'KENYA', 'X-3-LEVEL'),
('UNHCR', 'SECURITY', 'PREFAB'),
('UNHCR', 'UNHCR', NULL),
('UNHCR', 'UNHCR', 'PREFAB'),
('UNHCR', 'UNHCR', 'PREFAB-3'),
('UNHCR', 'UNHCR', 'PREFABs'),
('UNHCR', 'UNHCR', 'U-LEVEL-2'),
('UNHCR', 'UNHCR', 'UNHCR Prefabs'),
('UNHCR', 'UNHCR', 'X-2 EAST WING'),
('UNHCR', 'UNHCR', 'X-2 West Wing'),
('UNHCR', 'UNHCR', 'X-3 EAST WING'),
('UNHCR', 'UNHCR', 'X-3 WEST WING'),
('UNHCR', 'UNHCR', 'X-3-LEVEL'),

-- UNIC offices
('UNIC', 'UNIC', NULL),
('UNIC', 'UNIC', 'Cetral Area'),
('UNIC', 'UNIC', 'Sudan'),
('UNIC', 'UNIC', 'Upper Library'),
('UNIC', 'VS', 'Upper Library'),
('UNIC', 'VSA', NULL);

-- Continue with UNICEF offices (extensive)
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- UNICEF offices
('UNICEF', 'ESARO', 'D-205'),
('UNICEF', 'ESARO', 'F-104'),
('UNICEF', 'HQ/DCOE', 'U-LEVEL-1 EW'),
('UNICEF', 'HQ/PG', 'U-LEVEL-1 EW'),
('UNICEF', 'IRIN', 'X-3 EAST WING'),
('UNICEF', 'KCO', 'C-119'),
('UNICEF', 'KCO', 'C-120'),
('UNICEF', 'KCO', 'C-123'),
('UNICEF', 'KCO', 'C-126'),
('UNICEF', 'KCO', 'C-127'),
('UNICEF', 'KCO', 'C-128'),
('UNICEF', 'KCO', 'CW-207'),
('UNICEF', 'KCO', 'D-100'),
('UNICEF', 'KCO', 'D-102'),
('UNICEF', 'KCO', 'D-107'),
('UNICEF', 'KCO', 'D-110'),
('UNICEF', 'KCO', 'D-111'),
('UNICEF', 'KCO', 'D-112'),
('UNICEF', 'KCO', 'D-118'),
('UNICEF', 'KCO', 'D-123'),
('UNICEF', 'KCO', 'D-124'),
('UNICEF', 'KCO', 'D-136'),
('UNICEF', 'KCO', 'D-137'),
('UNICEF', 'KCO', 'D-200'),
('UNICEF', 'KCO', 'D-201'),
('UNICEF', 'KCO', 'D-207'),
('UNICEF', 'KCO', 'D-210'),
('UNICEF', 'KCO', 'D-211'),
('UNICEF', 'KCO', 'D-213'),
('UNICEF', 'KCO', 'D-218'),
('UNICEF', 'KCO', 'D-221'),
('UNICEF', 'KCO', 'D-223'),
('UNICEF', 'KCO', 'D-224'),
('UNICEF', 'KCO', 'D-225'),
('UNICEF', 'KCO', 'D-227'),
('UNICEF', 'KCO', 'D-230'),
('UNICEF', 'KCO', 'D-232'),
('UNICEF', 'KCO', 'D-233'),
('UNICEF', 'KCO', 'D-LEVEL-1'),
('UNICEF', 'KCO', 'Daadab'),
('UNICEF', 'KCO', 'Dadaab'),
('UNICEF', 'KCO', 'E-119'),
('UNICEF', 'KCO', 'E-123'),
('UNICEF', 'KCO', 'E-125'),
('UNICEF', 'KCO', 'E-126'),
('UNICEF', 'KCO', 'E-128'),
('UNICEF', 'KCO', 'E-133'),
('UNICEF', 'KCO', 'E-134'),
('UNICEF', 'KCO', 'E-202'),
('UNICEF', 'KCO', 'E-208'),
('UNICEF', 'KCO', 'E-219'),
('UNICEF', 'KCO', 'E-225'),
('UNICEF', 'KCO', 'E-226'),
('UNICEF', 'KCO', 'E-227'),
('UNICEF', 'KCO', 'E-231'),
('UNICEF', 'KCO', 'E-234'),
('UNICEF', 'KCO', 'E-237'),
('UNICEF', 'KCO', 'E-LEVEL-2'),
('UNICEF', 'KCO', 'F-101'),
('UNICEF', 'KCO', 'F-221'),
('UNICEF', 'KCO', 'F-227'),
('UNICEF', 'KCO', 'Garissa'),
('UNICEF', 'KCO', 'I-BLOCK'),
('UNICEF', 'KCO', 'KISUMU'),
('UNICEF', 'KCO', 'Kisumu Zonal Office'),
('UNICEF', 'KCO', 'Lodwar'),
('UNICEF', 'KCO', 'NOF BLOCK 4-GF NW'),
('UNICEF', 'KCO', 'Q-LELVEL-1'),
('UNICEF', 'KCO', 'Q-LEVEL-1'),
('UNICEF', 'KCO', 'Q-LEVEL-2'),
('UNICEF', 'KCO', 'Q-LEVEL-3'),
('UNICEF', 'KCO/ADMIN', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/CAP', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/CP', 'E-111'),
('UNICEF', 'KCO/CP', 'E-119'),
('UNICEF', 'KCO/CP', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/EDU', 'D-110'),
('UNICEF', 'KCO/EDU', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/EMER', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/FIN', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/GAR-ZO', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/HEALTH', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/HIV', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/HR', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/KAKUMA-ZO', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/LODWAR-ZO', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/MEETINGS', 'Old Cyber'),
('UNICEF', 'KCO/NUTRITION', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/PPME', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/QA', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/REPS-OFF', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/SBC', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/SECURITY', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/SP', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/SUP&LOG', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/T4D', 'U-LEVEL-2 EW'),
('UNICEF', 'KCO/WASH', 'U-LEVEL-2 EW'),
('UNICEF', 'RO', NULL);

-- Continue with more UNICEF and remaining organizations
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- More UNICEF RO offices
('UNICEF', 'RO', 'D-129'),
('UNICEF', 'RO', 'D-133'),
('UNICEF', 'RO', 'D-137'),
('UNICEF', 'RO', 'D-200'),
('UNICEF', 'RO', 'D-203'),
('UNICEF', 'RO', 'D-205'),
('UNICEF', 'RO', 'D-207'),
('UNICEF', 'RO', 'D-210'),
('UNICEF', 'RO', 'D-211'),
('UNICEF', 'RO', 'D-225'),
('UNICEF', 'RO', 'E-100'),
('UNICEF', 'RO', 'E-103'),
('UNICEF', 'RO', 'E-104'),
('UNICEF', 'RO', 'E-105'),
('UNICEF', 'RO', 'E-107'),
('UNICEF', 'RO', 'E-110'),
('UNICEF', 'RO', 'E-111'),
('UNICEF', 'RO', 'E-115'),
('UNICEF', 'RO', 'E-116'),
('UNICEF', 'RO', 'E-119'),
('UNICEF', 'RO', 'E-123'),
('UNICEF', 'RO', 'E-126'),
('UNICEF', 'RO', 'E-128'),
('UNICEF', 'RO', 'E-130'),
('UNICEF', 'RO', 'E-133'),
('UNICEF', 'RO', 'E-134'),
('UNICEF', 'RO', 'E-202'),
('UNICEF', 'RO', 'E-207'),
('UNICEF', 'RO', 'E-208'),
('UNICEF', 'RO', 'E-213'),
('UNICEF', 'RO', 'E-215'),
('UNICEF', 'RO', 'E-216'),
('UNICEF', 'RO', 'E-219'),
('UNICEF', 'RO', 'E-225'),
('UNICEF', 'RO', 'E-227'),
('UNICEF', 'RO', 'E-231'),
('UNICEF', 'RO', 'E-237'),
('UNICEF', 'RO', 'F-100A'),
('UNICEF', 'RO', 'F-100B'),
('UNICEF', 'RO', 'F-101'),
('UNICEF', 'RO', 'F-102'),
('UNICEF', 'RO', 'F-103'),
('UNICEF', 'RO', 'F-104A'),
('UNICEF', 'RO', 'F-105'),
('UNICEF', 'RO', 'F-108'),
('UNICEF', 'RO', 'F-200'),
('UNICEF', 'RO', 'F-201'),
('UNICEF', 'RO', 'F-202'),
('UNICEF', 'RO', 'F-203'),
('UNICEF', 'RO', 'F-204'),
('UNICEF', 'RO', 'F-206'),
('UNICEF', 'RO', 'F-207'),
('UNICEF', 'RO', 'F-208'),
('UNICEF', 'RO', 'F-209'),
('UNICEF', 'RO', 'F-210'),
('UNICEF', 'RO', 'F-215'),
('UNICEF', 'RO', 'F-216'),
('UNICEF', 'RO', 'F-217'),
('UNICEF', 'RO', 'F-218'),
('UNICEF', 'RO', 'F-219'),
('UNICEF', 'RO', 'F-221'),
('UNICEF', 'RO', 'F-222'),
('UNICEF', 'RO', 'F-224'),
('UNICEF', 'RO', 'F-225'),
('UNICEF', 'RO', 'F-226'),
('UNICEF', 'RO', 'Q-LEVEL-3'),
('UNICEF', 'RO', 'Residence'),
('UNICEF', 'RO', 'X-2 West Wing'),
('UNICEF', 'RO', 'X-3 EAST WING'),
('UNICEF', 'RO', 'X-BLOCK'),
('UNICEF', 'RO/ADM', 'B-215'),
('UNICEF', 'RO/COMM', 'X-BLOCK'),
('UNICEF', 'RO/CP', 'X-BLOCK'),
('UNICEF', 'RO/EDU', 'X-BLOCK'),
('UNICEF', 'RO/EVAL', 'X-BLOCK'),
('UNICEF', 'RO/Gender', 'X-BLOCK'),
('UNICEF', 'RO/HARP', 'X-BLOCK'),
('UNICEF', 'RO/HEALTH', 'X-BLOCK'),
('UNICEF', 'RO/HIV', 'X-BLOCK'),
('UNICEF', 'RO/HR', 'X-BLOCK'),
('UNICEF', 'RO/ICT/INNOV', 'X-BLK'),
('UNICEF', 'RO/ICT/INNOV', 'X-BLOCK'),
('UNICEF', 'RO/INNOV', NULL),
('UNICEF', 'RO/INNOV', 'E-126'),
('UNICEF', 'RO/INNOV', 'E-LEVEL-2'),
('UNICEF', 'RO/NUTRITION', 'X-BLOCK'),
('UNICEF', 'RO/OPERATIONS', 'X-BLOCK'),
('UNICEF', 'RO/ORD', 'X-BLOCK'),
('UNICEF', 'RO/PPM', 'X-BLOCK'),
('UNICEF', 'RO/PPP', 'X-BLOCK'),
('UNICEF', 'RO/SBC', 'X-BLOCK'),
('UNICEF', 'RO/SECURITY', 'X-BLOCK'),
('UNICEF', 'RO/SP', 'X-BLOCK'),
('UNICEF', 'RO/STAFF-COUN', 'X-BLOCK'),
('UNICEF', 'RO/SUPPLY', 'X-BLOCK'),
('UNICEF', 'RO/WASH', 'X-BLOCK'),
('UNICEF', 'RO/YOMA', 'X-BLOCK'),
('UNICEF', 'SOMALIA', 'D-100'),
('UNICEF', 'SOMALIA', 'D-110'),
('UNICEF', 'SOMALIA', 'D-123'),
('UNICEF', 'SOMALIA', 'D-LEVEL-1'),
('UNICEF', 'SOMALIA', 'Q-LELVEL-1'),
('UNICEF', 'SOMALIA', 'Q-LEVEL-1'),
('UNICEF', 'SOMALIA', 'Q-LEVEL-2'),
('UNICEF', 'SOMALIA', 'Q-SECOND-LEVEL'),
('UNICEF', 'SOMALIA', 'ROOF TOP'),

-- UNICEN offices
('UNICEN', 'KCO', 'B-231'),
('UNICEN', 'KCO', 'C-120'),
('UNICEN', 'KCO', 'C-126'),
('UNICEN', 'KCO', 'D-123'),
('UNICEN', 'KCO', 'D-136'),
('UNICEN', 'KCO', 'D-207'),
('UNICEN', 'KCO', 'D-213'),
('UNICEN', 'KCO', 'D-225'),
('UNICEN', 'KCO', 'E-116'),
('UNICEN', 'KCO', 'E-219'),
('UNICEN', 'KCO', 'E-231'),
('UNICEN', 'KCO', 'E-234'),
('UNICEN', 'KCO', 'F-201'),
('UNICEN', 'KCO', 'Q-LEVEL-2'),
('UNICEN', 'KCO', 'Q-LEVEL-3'),
('UNICEN', 'RO', 'E-111'),
('UNICEN', 'RO', 'E-133'),
('UNICEN', 'UNICEN', 'BLK'),
('UNICEN', 'UNICEN', 'CENTRAL AREA'),
('UNICEN', 'UNICEN', 'Cetral Area'),
('UNICEN', 'UNICEN', 'Lower Library'),
('UNICEN', 'UNICEN', 'R-205'),
('UNICEN', 'UNICEN', 'UNIC'),
('UNICEN', 'UNICEN', 'UNICEN'),
('UNICEN', 'UNICEN', 'UPPER LIB'),
('UNICEN', 'UNICEN', 'UPPER LIBRARY'),
('UNICEN', 'UNIS', 'Central Area'),
('UNICEN', 'UNIS', 'Cetral Area'),
('UNICEN', 'UNIS', 'V-BLK'),
('UNICEN', 'VS', 'Upper Lib'),
('UNICEN', 'VS', 'Upper Library'),

-- UNICRI offices
('UNICRI', 'UNICRI', NULL),
('UNICRI', 'UNICRI', 'U-LEVEL-2'),
('UNICRI', 'UNICRI', 'UNON, BLOCK U,'),

-- UNIDO offices
('UNIDO', 'TRANSPORT', NULL),
('UNIDO', 'UNIDO', 'N-BLOCK-1'),
('UNIDO', 'UNIDO', 'N-LEVEL-1'),

-- UNISDR offices
('UNISDR', 'UNISDR', 'N-2 OPEN'),
('UNISDR', 'UNISDR', 'N-LEVEL-2'),

-- UNITAMS offices
('UNITAMS', 'CMS', 'W-BLK'),
('UNITAMS', 'COS', 'W-BLK'),
('UNITAMS', 'ORM', 'Block  W-101'),
('UNITAMS', 'POL', 'Block W - 101'),
('UNITAMS', 'POL', 'W-BLK'),
('UNITAMS', 'SCP', 'W-BLK'),
('UNITAMS', 'SRSGNA', 'Block W - 101'),
('UNITAMS', 'SRSGNA', 'Block W -101'),
('UNITAMS', 'SRSGNA', 'Block W 101'),
('UNITAMS', 'SRSGNA', 'Block W- 101'),
('UNITAMS', 'SRSGNA', 'W-BLK'),
('UNITAMS', 'UNITAMS', 'W-1 WEST WING'),

-- UNKLESA offices
('UNKLESA', 'UNKLESA', 'G-210'),

-- UNMC offices
('UNMC', 'UNMC', 'N-LEVEL-1'),

-- UNOCHA offices
('UNOCHA', 'FPRC', 'V-BLK'),
('UNOCHA', 'FPRC', 'W-BLK'),
('UNOCHA', 'IRIN', 'UNOCHA HOUSE'),
('UNOCHA', 'IRIN', 'UNOCHA/HOUSE'),
('UNOCHA', 'IRIN', 'UNOCHA/IRIN'),
('UNOCHA', 'IRIN', 'X-3 EAST WING'),
('UNOCHA', 'KENYA', 'X-3 EAST WING'),
('UNOCHA', 'KENYA', 'X-3 WEST WING'),
('UNOCHA', 'ROSEA', 'X-BLK'),
('UNOCHA', 'SOMALIA', NULL),
('UNOCHA', 'SOMALIA', 'PREFAB-D1'),
('UNOCHA', 'SOMALIA', 'W-BLK'),
('UNOCHA', 'SOMALIA', 'X-2 EAST WING'),
('UNOCHA', 'SOMALIA', 'X-3 EAST WING'),
('UNOCHA', 'SROEA', 'X-3 EAST WING'),
('UNOCHA', 'SROEA', 'X-3 WEST WING');

-- Continue with remaining organizations
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- UNODC offices
('UNODC', 'ACP', 'UNODC/ACP'),
('UNODC', 'ACP', 'X-2 West Wing'),
('UNODC', 'CJP', 'X-2 West Wing'),
('UNODC', 'Corruption Hub', NULL),
('UNODC', 'CPP', 'X-2 West Wing'),
('UNODC', 'CTP', 'X-2 West Wing'),
('UNODC', 'FO', 'X-2 West Wing'),
('UNODC', 'FO', 'X-BLK'),
('UNODC', 'GMCP', NULL),
('UNODC', 'GMCP', 'NEW-BLK'),
('UNODC', 'GMCP', 'X-BLK'),
('UNODC', 'HEALTH', 'X-BLK'),
('UNODC', 'HL', 'X-2 West Wing'),
('UNODC', 'OMS', 'X-2 West Wing'),
('UNODC', 'ROEA', 'X-BLK'),
('UNODC', 'UNODC', 'Annex Y'),
('UNODC', 'UNODC', 'BLOCK - X'),
('UNODC', 'UNODC', 'Block X Level 2'),
('UNODC', 'UNODC', 'M-BLK'),
('UNODC', 'UNODC', 'Mombasa'),
('UNODC', 'UNODC', 'Prefabs'),
('UNODC', 'UNODC', 'V-1 East Wing'),
('UNODC', 'UNODC', 'V-BLK'),
('UNODC', 'UNODC', 'W-LEVEL-2 West Wing'),
('UNODC', 'UNODC', 'X-2 EAST WING'),
('UNODC', 'UNODC', 'X-2 West Wing'),
('UNODC', 'UNODC', 'X-2 WW'),
('UNODC', 'UNODC', 'X-3 WEST WING'),
('UNODC', 'UNODC', 'X-BLKL'),
('UNODC', 'UNODC', 'x-l'),
('UNODC', 'UNODC', 'X-LEVEL-3'),
('UNODC', 'UNODC DO RSAME ROEA', NULL),
('UNODC', 'UNODC DO RSAME ROEA', 'X-BLK'),
('UNODC', 'UNODC ROEA', NULL),
('UNODC', 'UNODC ROEA', 'x-blk'),

-- UNOPS offices
('UNOPS', 'IRIN', 'X-3 EAST WING'),
('UNOPS', 'RO', 'UNOPS ANNEX'),
('UNOPS', 'SOMALIA', 'UNOPS ANNEX'),
('UNOPS', 'UNMAS', NULL),
('UNOPS', 'UNMAS', 'R-LEVEL-1'),
('UNOPS', 'UNMAS', 'UNOPS ANNEX'),
('UNOPS', 'UNOPS', 'N-334'),
('UNOPS', 'UNOPS', 'PREFAB-10'),
('UNOPS', 'UNOPS', 'PREFAB-8'),
('UNOPS', 'UNOPS', 'Q-LEVEL-2'),
('UNOPS', 'UNOPS', 'UNOPS ANNEX'),
('UNOPS', 'UNOPS', 'UNPOS ANNEX'),
('UNOPS', 'UNOPS', 'V-3 EAST WING'),
('UNPD', 'GEF/SGP', 'M-LEVEL-2'),
('UNPD', 'GEF/SGP', 'N-LEVEL-1'),

-- UNPOS offices
('UNPOS', 'UNPOS', 'PREFAB-10'),
('UNPOS', 'UNPOS', 'PREFAB-11'),
('UNPOS', 'UNPOS', 'PREFAB-13'),
('UNPOS', 'UNPOS', 'PREFAB-14'),
('UNPOS', 'UNPOS', 'PREFAB-4'),
('UNPOS', 'UNPOS', 'PREFAB-5'),
('UNPOS', 'UNPOS', 'PREFAB-6'),
('UNPOS', 'UNPOS', 'PREFAB-7'),
('UNPOS', 'UNPOS', 'UNPOS ANNEX'),

-- UNSOA offices
('UNSOA', 'AUDITORS', 'PREFAB-5'),
('UNSOA', 'UNSOA', 'I-209'),
('UNSOA', 'UNSOA', 'Nairobi'),
('UNSOA', 'UNSOA', 'PREFAB-1'),
('UNSOA', 'UNSOA', 'PREFAB-10'),
('UNSOA', 'UNSOA', 'PREFAB-12'),
('UNSOA', 'UNSOA', 'PREFAB-2'),
('UNSOA', 'UNSOA', 'PREFAB-5'),
('UNSOA', 'UNSOA', 'PREFAB-6'),
('UNSOA', 'UNSOA', 'PREFAB-7'),
('UNSOA', 'UNSOA', 'PREFAB-8'),
('UNSOA', 'UNSOA', 'PREFAB-9'),
('UNSOA', 'UNSOA', 'T-LEVEL-2'),
('UNSOA', 'UNSOA', 'T-LEVEL-3'),

-- UNSOS offices
('UNSOS', 'UNSOS', 'S-LEVEL-2'),

-- UNWOMEN offices
('UNWOMEN', 'KENYA', 'N-BLOCK-1');

-- Continue with WFP offices (extensive)
INSERT INTO #TempOfficeData (OrgCode, OfficeName, SubOfficeName) VALUES
-- WFP offices
('WFP', 'FINANCE', 'A-213'),
('WFP', 'HQ/SEC', 'PREFAB-D2'),
('WFP', 'INV', 'M-LEVEL-2'),
('WFP', 'KCO', 'A-108'),
('WFP', 'KCO', 'A-112'),
('WFP', 'KCO', 'A-114'),
('WFP', 'KCO', 'A-124'),
('WFP', 'KCO', 'A-128'),
('WFP', 'KCO', 'A-132'),
('WFP', 'KCO', 'A-201'),
('WFP', 'KCO', 'A-215'),
('WFP', 'KCO', 'A-219'),
('WFP', 'KCO', 'A-222'),
('WFP', 'KCO', 'A-228'),
('WFP', 'KCO', 'B-204'),
('WFP', 'KCO', 'B-205'),
('WFP', 'KCO', 'B-209'),
('WFP', 'KCO', 'B-216'),
('WFP', 'KCO', 'B-222'),
('WFP', 'KCO', 'B-227'),
('WFP', 'KCO', 'B-236'),
('WFP', 'KCO', 'C-100'),
('WFP', 'KCO', 'Daadab'),
('WFP', 'KCO', 'M-2 OPEN SPACE'),
('WFP', 'KCO', 'M-LEVEL-2'),
('WFP', 'KCO', 'V-1  WEST WING'),
('WFP', 'KCO', 'WFP Annex'),
('WFP', 'KCO/ADM', 'A-201'),
('WFP', 'KCO/ADM', 'A-205'),
('WFP', 'KCO/ADM', 'A-211'),
('WFP', 'KCO/ADM', 'A-213'),
('WFP', 'KCO/ADM', 'A-219'),
('WFP', 'KCO/ADM', 'A-226'),
('WFP', 'KCO/ADM', 'A-232'),
('WFP', 'KCO/ADM', 'ARCHIVES'),
('WFP', 'KCO/ADM', 'B-115'),
('WFP', 'KCO/ADM', 'B-119'),
('WFP', 'KCO/ADM', 'B-215'),
('WFP', 'KCO/ADM', 'B-220'),
('WFP', 'KCO/ADM', 'B-223'),
('WFP', 'KCO/ADM', 'B-227'),
('WFP', 'KCO/ADM', 'B-235'),
('WFP', 'KCO/ADM', 'C-101'),
('WFP', 'KCO/ADM', 'M-LEVEL-1'),
('WFP', 'KCO/ADM', 'M-LEVEL-2'),
('WFP', 'KCO/CP', 'A-201'),
('WFP', 'KCO/CP', 'A-205'),
('WFP', 'KCO/CP', 'B-205'),
('WFP', 'KCO/CP', 'B-234'),
('WFP', 'KCO/FIN', 'A-114'),
('WFP', 'KCO/FIN', 'A-204'),
('WFP', 'KCO/FIN', 'A-212'),
('WFP', 'KCO/FIN-ADMIN', 'A-201'),
('WFP', 'KCO/FINANCE', 'A-211'),
('WFP', 'KCO/HR', 'B-126'),
('WFP', 'KCO/HR', 'B-128'),
('WFP', 'KCO/HR', 'B-129'),
('WFP', 'KCO/ICT', 'A-114'),
('WFP', 'KCO/ICT', 'A-205'),
('WFP', 'KCO/ICT', 'A-222'),
('WFP', 'KCO/ICT', 'B-204'),
('WFP', 'KCO/ICT', 'B-223'),
('WFP', 'KCO/ICT', 'B-231'),
('WFP', 'KCO/ICT', 'B-233'),
('WFP', 'KCO/ICT', 'B-235'),
('WFP', 'KCO/ICT', 'B-237'),
('WFP', 'KCO/INNOV', 'A-100'),
('WFP', 'KCO/INNOV', 'A-108'),
('WFP', 'KCO/INNOV', 'A-116'),
('WFP', 'KCO/INNOV', 'A-226'),
('WFP', 'KCO/INNOV', 'B-103'),
('WFP', 'KCO/INNOV', 'B-222'),
('WFP', 'KCO/INNOV', 'C-100'),
('WFP', 'KCO/LOG', 'A-114'),
('WFP', 'KCO/LOG', 'A-132'),
('WFP', 'KCO/LOG', 'A-134'),
('WFP', 'KCO/LOG', 'A-212'),
('WFP', 'KCO/LOG', 'B-100'),
('WFP', 'KCO/LOG', 'B-103'),
('WFP', 'KCO/LOG', 'B-104'),
('WFP', 'KCO/LOG', 'B-107'),
('WFP', 'KCO/LOG', 'B-108'),
('WFP', 'KCO/LOG', 'B-116'),
('WFP', 'KCO/LOG', 'B-124'),
('WFP', 'KCO/LOG', 'B-233'),
('WFP', 'KCO/LOG', 'BA08'),
('WFP', 'KCO/LOG', 'C-100'),
('WFP', 'KCO/LOG', 'M-LEVEL-2'),
('WFP', 'KCO/M&E', 'B-223'),
('WFP', 'KCO/NASATO', 'A-100'),
('WFP', 'KCO/NASATO', 'A-114'),
('WFP', 'KCO/NASATO', 'B-133'),
('WFP', 'KCO/NASATO', 'B-234'),
('WFP', 'KCO/P4P', 'B-226'),
('WFP', 'KCO/P4P', 'B-234'),
('WFP', 'KCO/PPLINE', 'A-120'),
('WFP', 'KCO/PRO', 'A-219'),
('WFP', 'KCO/PRO', 'A-222'),
('WFP', 'KCO/PRO', 'B-210'),
('WFP', 'KCO/PRO', 'I-104'),
('WFP', 'KCO/PROC', 'A-114'),
('WFP', 'KCO/PROC', 'A-131'),
('WFP', 'KCO/PROC', 'A-205'),
('WFP', 'KCO/PROC', 'A-211'),
('WFP', 'KCO/PROC', 'A-222'),
('WFP', 'KCO/PROC', 'B-124'),
('WFP', 'KCO/PROC', 'B-213'),
('WFP', 'KCO/PROC', 'B-222'),
('WFP', 'KCO/PROC', 'B-226'),
('WFP', 'KCO/PROC', 'Daadab'),
('WFP', 'KCO/PRRO', 'B-205'),
('WFP', 'KCO/RADIO', 'B-115'),
('WFP', 'KCO/RECOV', 'A-100'),
('WFP', 'KCO/RECOV', 'A-132'),
('WFP', 'KCO/RECOV', 'A-219'),
('WFP', 'KCO/RECOV', 'A-225'),
('WFP', 'KCO/RECOV', 'A-228'),
('WFP', 'KCO/RECOV', 'A-232'),
('WFP', 'KCO/RECOV', 'B-124'),
('WFP', 'KCO/RECOV', 'B-213'),
('WFP', 'KCO/REF', 'B-209'),
('WFP', 'KCO/SEC', 'A-100'),
('WFP', 'KCO/SEC', 'A-213'),
('WFP', 'KCO/TU', 'C-100'),
('WFP', 'KCO/UNCAS', 'A-216'),
('WFP', 'KCO/VAM', 'A-132'),
('WFP', 'KCO/VAM', 'B-213'),
('WFP', 'KCO/VAM', 'B-214'),
('WFP', 'KCO/VAM', 'C-100'),
('WFP', 'KCO/VAM', 'PREFAB'),
('WFP', 'LOG', 'C-100'),
('WFP', 'PRRO', 'B-209'),
('WFP', 'RB', 'A-104'),
('WFP', 'RB', 'A-123'),
('WFP', 'RB', 'A-219'),
('WFP', 'RB', 'A-224'),
('WFP', 'RB', 'I-103'),
('WFP', 'RB', 'I-104'),
('WFP', 'RB', 'I-111'),
('WFP', 'RB', 'I-123'),
('WFP', 'RB', 'I-131'),
('WFP', 'RB', 'I-134'),
('WFP', 'RB', 'I-214'),
('WFP', 'RB', 'I-218'),
('WFP', 'RB', 'I-220'),
('WFP', 'RB', 'I-222'),
('WFP', 'RB', 'I-223'),
('WFP', 'RB', 'I-BLOCK'),
('WFP', 'RB', 'I-BLOCK-2'),
('WFP', 'RB', 'New Commissary Bld'),
('WFP', 'RB', 'X-Block'),
('WFP', 'RB/ADM', 'I-BLOCK'),
('WFP', 'RB/ADM', 'I-LEVEL-1'),
('WFP', 'RB/ADM', 'PREFAB'),
('WFP', 'RB/CV', 'I-125'),
('WFP', 'RB/EMP', 'I-116'),
('WFP', 'RB/EMP', 'I-204'),
('WFP', 'RB/EMP', 'J-BLOCK'),
('WFP', 'RB/ER', 'A-114'),
('WFP', 'RB/FIN', 'I-103'),
('WFP', 'RB/FIN', 'I-BLOCK'),
('WFP', 'RB/FIN-ADMIN', 'A-123'),
('WFP', 'RB/FIN-ADMIN', 'A-223'),
('WFP', 'RB/FIN-ADMIN', 'I-100'),
('WFP', 'RB/FIN-ADMIN', 'I-102'),
('WFP', 'RB/FIN-ADMIN', 'I-103'),
('WFP', 'RB/FIN-ADMIN', 'I-104'),
('WFP', 'RB/FIN-ADMIN', 'I-129'),
('WFP', 'RB/FIN-ADMIN', 'I-222'),
('WFP', 'RB/FIN-ADMIN', 'V-1  WEST WING'),
('WFP', 'RB/FN', 'B-116'),
('WFP', 'RB/FN', 'I-104'),
('WFP', 'RB/FN', 'I-214'),
('WFP', 'RB/GMS', 'I-130'),
('WFP', 'RB/HR', 'I-203'),
('WFP', 'RB/HR', 'I-207'),
('WFP', 'RB/ICT', 'A-113'),
('WFP', 'RB/INF', 'A-108'),
('WFP', 'RB/INF', 'A-121'),
('WFP', 'RB/INF', 'A-201'),
('WFP', 'RB/ITCC', 'A-109'),
('WFP', 'RB/ITCC', 'I-126'),
('WFP', 'RB/ITCC', 'V-1  WEST WING'),
('WFP', 'RB/LOG', 'A-104'),
('WFP', 'RB/LOG', 'A-105'),
('WFP', 'RB/LOG', 'I-105'),
('WFP', 'RB/LOG', 'I-134'),
('WFP', 'RB/M&E', 'A-211'),
('WFP', 'RB/M&E', 'I-204'),
('WFP', 'RB/MA', 'I-123'),
('WFP', 'RB/PROC', 'A-113'),
('WFP', 'RB/PROC', 'I-103'),
('WFP', 'RB/PROC', 'I-LEVEL-1'),
('WFP', 'RB/PROG', 'A-106'),
('WFP', 'RB/PROG', 'A-223'),
('WFP', 'RB/PROG', 'I-103'),
('WFP', 'RB/PROG', 'I-114'),
('WFP', 'RB/PROG', 'I-123'),
('WFP', 'RB/PROG', 'I-129'),
('WFP', 'RB/PROG', 'I-214'),
('WFP', 'RB/PROG', 'I-223'),
('WFP', 'RB/PROG', 'I-BLOCK'),
('WFP', 'RB/RAS', 'I-122'),
('WFP', 'RB/RAS', 'I-123'),
('WFP', 'RB/RMMI', 'A-104'),
('WFP', 'RB/RMP', 'A-123'),
('WFP', 'RB/RMP', 'A-127'),
('WFP', 'RB/RMP', 'I-215'),
('WFP', 'RB/SC', 'A-101'),
('WFP', 'RB/SC', 'A-104'),
('WFP', 'RB/SC', 'A-117'),
('WFP', 'RB/SC', 'B-117'),
('WFP', 'RB/SC', 'I-106'),
('WFP', 'RB/SC', 'PREFABs'),
('WFP', 'RB/SC', 'X-2 EAST WING'),
('WFP', 'RB/SEC', 'A-114'),
('WFP', 'RB/SEC', 'I-110'),
('WFP', 'RB/SEC', 'I-111'),
('WFP', 'RB/SEC', 'I-114'),
('WFP', 'RB/SUD', 'I-111'),
('WFP', 'RB/VAM', 'I-114'),
('WFP', 'RB/VAM', 'I-121'),
('WFP', 'RB/VAM', 'I-123'),
('WFP', 'RB/VAM', 'I-126'),
('WFP', 'RB/VAM', 'I-214'),
('WFP', 'RO', 'A-222'),
('WFP', 'RO', 'E-235'),
('WFP', 'RO/CO', 'A-219'),
('WFP', 'SOMALIA', 'WFP SOMALIA ANNEX'),

-- WHO offices
('WHO', 'HQ/SEC', 'PREFAB-D2'),
('WHO', 'KCO', 'U-LEVEL-3'),
('WHO', 'SOM', 'PREFAB-D2'),
('WHO', 'SOMALIA', 'PREFAB-D2'),
('WHO', 'SOMALIA', 'WHO ANNEX'),
('WHO', 'WHO', 'WHO'),
('WHO', 'WHO', 'WHO ANNEX'),

-- WMO offices
('WMO', 'WMO', 'P-LEVEL-2'),
('WMO', 'WMO', 'P-LEVEL-3'),
('WMO', 'WMO', 'PREFAB'),
('WMO', 'WMO', 'Prefabs');

-- Now process the data
DECLARE @OrgId INT;
DECLARE @OfficeId INT;
DECLARE @OfficeName NVARCHAR(200);
DECLARE @SubOfficeName NVARCHAR(200);
DECLARE @CreatedCount INT = 0;
DECLARE @OfficeCount INT = 0;
DECLARE @SubOfficeCount INT = 0;

-- Process each unique organization/office combination
DECLARE office_cursor CURSOR FOR
    SELECT DISTINCT OrgCode, OfficeName
    FROM #TempOfficeData
    WHERE OfficeName IS NOT NULL
    ORDER BY OrgCode, OfficeName;

OPEN office_cursor;
FETCH NEXT FROM office_cursor INTO @OrgCode, @OfficeName;

WHILE @@FETCH_STATUS = 0
BEGIN
    -- Get the Organization ID
    SELECT @OrgId = Id FROM Organizations WHERE Code = @OrgCode;

    IF @OrgId IS NOT NULL
    BEGIN
        -- Check if office already exists
        IF NOT EXISTS (SELECT 1 FROM Offices WHERE Name = @OfficeName AND OrganizationId = @OrgId)
        BEGIN
            -- Create the office
            INSERT INTO Offices (Name, Code, OrganizationId, CreatedDate, CreatedBy)
            VALUES (@OfficeName,
                    LEFT(REPLACE(REPLACE(@OfficeName, '/', ''), ' ', ''), 10), -- Simple code generation
                    @OrgId,
                    GETUTCDATE(),
                    'System');

            SET @OfficeCount = @OfficeCount + 1;
        END
    END

    FETCH NEXT FROM office_cursor INTO @OrgCode, @OfficeName;
END

CLOSE office_cursor;
DEALLOCATE office_cursor;

-- Process suboffices
DECLARE suboffice_cursor CURSOR FOR
    SELECT OrgCode, OfficeName, SubOfficeName
    FROM #TempOfficeData
    WHERE SubOfficeName IS NOT NULL
    ORDER BY OrgCode, OfficeName, SubOfficeName;

OPEN suboffice_cursor;
FETCH NEXT FROM suboffice_cursor INTO @OrgCode, @OfficeName, @SubOfficeName;

WHILE @@FETCH_STATUS = 0
BEGIN
    -- Get the Organization ID
    SELECT @OrgId = Id FROM Organizations WHERE Code = @OrgCode;

    IF @OrgId IS NOT NULL
    BEGIN
        -- Get the Office ID
        SELECT @OfficeId = Id FROM Offices WHERE Name = @OfficeName AND OrganizationId = @OrgId;

        IF @OfficeId IS NOT NULL
        BEGIN
            -- Check if suboffice already exists
            IF NOT EXISTS (SELECT 1 FROM SubOffices WHERE Name = @SubOfficeName AND OfficeId = @OfficeId)
            BEGIN
                -- Create the suboffice
                INSERT INTO SubOffices (Name, Code, OfficeId, CreatedDate, CreatedBy)
                VALUES (@SubOfficeName,
                        LEFT(REPLACE(REPLACE(@SubOfficeName, ' ', ''), '-', ''), 10), -- Simple code generation
                        @OfficeId,
                        GETUTCDATE(),
                        'System');

                SET @SubOfficeCount = @SubOfficeCount + 1;
            END
        END
    END

    FETCH NEXT FROM suboffice_cursor INTO @OrgCode, @OfficeName, @SubOfficeName;
END

CLOSE suboffice_cursor;
DEALLOCATE suboffice_cursor;

-- Clean up temp table
DROP TABLE #TempOfficeData;

-- Final report
PRINT '';
PRINT '================================================================';
PRINT 'OFFICE AND SUBOFFICE SEEDING COMPLETE';
PRINT '================================================================';
PRINT 'Offices created: ' + CAST(@OfficeCount AS NVARCHAR(10));
PRINT 'SubOffices created: ' + CAST(@SubOfficeCount AS NVARCHAR(10));
PRINT '';

-- Show summary by organization
SELECT
    o.Code as Organization,
    COUNT(DISTINCT ofc.Id) as OfficeCount,
    COUNT(DISTINCT so.Id) as SubOfficeCount
FROM Organizations o
LEFT JOIN Offices ofc ON o.Id = ofc.OrganizationId
LEFT JOIN SubOffices so ON ofc.Id = so.OfficeId
WHERE o.Code IN ('CON', 'DSS', 'FAO', 'ICAO', 'ICC', 'ICC-CPI', 'IFAD', 'ILO', 'IMO',
                  'OHCHR', 'OIOS', 'OSESG', 'POESOM', 'RCO', 'RCS', 'UN-WOMEN', 'UNAIDS',
                  'UNAMIS', 'UNCRD', 'UNDEFINED', 'UNDP', 'UNDP-REDD+', 'UNDRR', 'UNDSS',
                  'UNDT', 'UNEP ODED', 'UNESCO', 'UNFPA', 'UNHCR', 'UNIC', 'UNICEF',
                  'UNICEN', 'UNICRI', 'UNIDO', 'UNISDR', 'UNITAMS', 'UNKLESA', 'UNMC',
                  'UNOCHA', 'UNODC', 'UNOPS', 'UNPD', 'UNPOS', 'UNSOA', 'UNSOS', 'UNWOMEN',
                  'WFP', 'WHO', 'WMO')
GROUP BY o.Code
ORDER BY o.Code;

PRINT '';
PRINT '✅ ALL OFFICES AND SUBOFFICES HAVE BEEN SEEDED SUCCESSFULLY!';
GO