// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using TAB.Web.Data;

#nullable disable

namespace TAB.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002123541_AddVerificationPeriodToCallRecords")]
    partial class AddVerificationPeriodToCallRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal migration - only tracks the verification_period column addition
            // Full model snapshot is maintained in ApplicationDbContextModelSnapshot.cs
        }
    }
}
